# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Thomas Ibel'
tagline:          'Experiments'
description:      'Software Developer from Austria'
url:              https://tibel.github.io/
baseurl:          /

author:
  name:           'Thomas Ibel'
  twitter:        thomasibel
  github:         tibel
  stackoverflow:  3333371/tibel

# Pagination
paginate:         5
